<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-R2K6MVF" failures="49" tests="145" name="Command line test" time="9.573" errors="0" timestamp="2021-04-27T09:23:07 ICT">
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testDeleteWithNullMacd" time="0.04">
    <failure type="org.testng.TestException" message="
Method ChuyenDeDaoNGTest.testDeleteWithNullMacd()[pri:0, instance:edu.poly.dao.ChuyenDeDaoNGTest_$$_jvstcfb_0@763cf5b9] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method ChuyenDeDaoNGTest.testDeleteWithNullMacd()[pri:0, instance:edu.poly.dao.ChuyenDeDaoNGTest_$$_jvstcfb_0@763cf5b9] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteWithNullMacd -->
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testDeleteWithValidMacd" time="0.002"/>
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testFindByIdWithNotFoundMacd" time="0.044"/>
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testFindByIdWithValidMacd" time="0.002"/>
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testInsertWithEmptyModel" time="0.0">
    <failure type="org.testng.TestException" message="
Method ChuyenDeDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.ChuyenDeDaoNGTest_$$_jvstcfb_0@763cf5b9] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method ChuyenDeDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.ChuyenDeDaoNGTest_$$_jvstcfb_0@763cf5b9] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testInsertWithEmptyModel -->
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testInsertWithNullModel" time="0.0"/>
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testInsertWithValidModel" time="0.0"/>
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testSelect" time="0.016"/>
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testUpdateWithEmptyModel" time="0.001">
    <failure type="org.testng.TestException" message="
Method ChuyenDeDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.ChuyenDeDaoNGTest_$$_jvstcfb_0@763cf5b9] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method ChuyenDeDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.ChuyenDeDaoNGTest_$$_jvstcfb_0@763cf5b9] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateWithEmptyModel -->
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testUpdateWithNullModel" time="0.001"/>
  <testcase classname="edu.poly.dao.ChuyenDeDaoNGTest" name="testUpdateWithValidModel" time="0.001"/>
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testDeleteWithMahv" time="0.022"/>
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testDeleteWithNullMahv" time="0.002">
    <failure type="org.testng.TestException" message="
Method HocVienDaoNGTest.testDeleteWithNullMahv()[pri:0, instance:edu.poly.dao.HocVienDaoNGTest_$$_jvstffa_0@71f0b72e] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method HocVienDaoNGTest.testDeleteWithNullMahv()[pri:0, instance:edu.poly.dao.HocVienDaoNGTest_$$_jvstffa_0@71f0b72e] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteWithNullMahv -->
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testFindByIdWithNotFoundMahv" time="0.021"/>
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testFindByIdWithValidMahv" time="0.003"/>
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testInsertWithEmptyModel" time="0.002">
    <failure type="org.testng.TestException" message="
Method HocVienDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.HocVienDaoNGTest_$$_jvstffa_0@71f0b72e] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method HocVienDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.HocVienDaoNGTest_$$_jvstffa_0@71f0b72e] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testInsertWithEmptyModel -->
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testInsertWithNullModel" time="0.003"/>
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testInsertWithValidModel" time="0.0"/>
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testSelect" time="0.009"/>
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testUpdateWithEmptyModel" time="0.001">
    <failure type="org.testng.TestException" message="
Method HocVienDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.HocVienDaoNGTest_$$_jvstffa_0@71f0b72e] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method HocVienDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.HocVienDaoNGTest_$$_jvstffa_0@71f0b72e] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateWithEmptyModel -->
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testUpdateWithNullModel" time="0.001"/>
  <testcase classname="edu.poly.dao.HocVienDaoNGTest" name="testUpdateWithValidModel" time="0.001"/>
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testDeleteWithNull" time="0.021">
    <failure type="org.testng.TestException" message="
Method KhoaHocDaoNGTest.testDeleteWithNull()[pri:0, instance:edu.poly.dao.KhoaHocDaoNGTest_$$_jvstb41_0@7a34f66a] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method KhoaHocDaoNGTest.testDeleteWithNull()[pri:0, instance:edu.poly.dao.KhoaHocDaoNGTest_$$_jvstb41_0@7a34f66a] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteWithNull -->
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testDeleteWithValid" time="0.001"/>
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testFindByIdWithNotFoundID" time="0.017"/>
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testFindByIdWithValidID" time="0.05"/>
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testInsertWithEmptyModel" time="0.0">
    <failure type="org.testng.TestException" message="
Method KhoaHocDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.KhoaHocDaoNGTest_$$_jvstb41_0@7a34f66a] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method KhoaHocDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.KhoaHocDaoNGTest_$$_jvstb41_0@7a34f66a] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testInsertWithEmptyModel -->
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testInsertWithNullModel" time="0.0"/>
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testInsertWithValid" time="0.014"/>
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testSelect" time="0.004"/>
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testUpdateWithEmptyModel" time="0.001">
    <failure type="org.testng.TestException" message="
Method KhoaHocDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.KhoaHocDaoNGTest_$$_jvstb41_0@7a34f66a] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method KhoaHocDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.KhoaHocDaoNGTest_$$_jvstb41_0@7a34f66a] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateWithEmptyModel -->
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testUpdateWithNullModel" time="0.002"/>
  <testcase classname="edu.poly.dao.KhoaHocDaoNGTest" name="testUpdateWithValidModel" time="0.0"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testDeleteWithNullId" time="0.021">
    <failure type="org.testng.TestException" message="
Method NguoiHocDaoNGTest.testDeleteWithNullId()[pri:0, instance:edu.poly.dao.NguoiHocDaoNGTest_$$_jvstfad_0@2f508f3c] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method NguoiHocDaoNGTest.testDeleteWithNullId()[pri:0, instance:edu.poly.dao.NguoiHocDaoNGTest_$$_jvstfad_0@2f508f3c] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteWithNullId -->
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testDeleteWithValidId" time="0.004"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testFindByIdNotFound" time="0.009"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testFindByIdWithFound" time="0.003"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testInsertWithEmptyModel" time="0.002">
    <failure type="org.testng.TestException" message="
Method NguoiHocDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.NguoiHocDaoNGTest_$$_jvstfad_0@2f508f3c] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method NguoiHocDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.NguoiHocDaoNGTest_$$_jvstfad_0@2f508f3c] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testInsertWithEmptyModel -->
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testInsertWithNullModel" time="0.0"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testInsertWithValidModel" time="0.022"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testSelect" time="0.0"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testSelectByCourseWithFound" time="0.002"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testSelectByCourseWithNotFound" time="0.002"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testSelectByKeyword" time="0.002"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testUpdateWithEmptyModel" time="0.001">
    <failure type="org.testng.TestException" message="
Method NguoiHocDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.NguoiHocDaoNGTest_$$_jvstfad_0@2f508f3c] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method NguoiHocDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.NguoiHocDaoNGTest_$$_jvstfad_0@2f508f3c] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateWithEmptyModel -->
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testUpdateWithNullModel" time="0.001"/>
  <testcase classname="edu.poly.dao.NguoiHocDaoNGTest" name="testUpdateWithValidModel" time="0.002"/>
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testDeleteWithNullMahv" time="0.003">
    <failure type="org.testng.TestException" message="
Method NhanVienDaoNGTest.testDeleteWithNullMahv()[pri:0, instance:edu.poly.dao.NhanVienDaoNGTest_$$_jvstabe_0@3ed03652] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method NhanVienDaoNGTest.testDeleteWithNullMahv()[pri:0, instance:edu.poly.dao.NhanVienDaoNGTest_$$_jvstabe_0@3ed03652] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteWithNullMahv -->
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testDeleteWithValidMahv" time="0.001"/>
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testFindByIdWithFound" time="0.021"/>
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testFindByIdWithNotFound" time="0.002"/>
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testInsertWithEmptyModel" time="0.002">
    <failure type="org.testng.TestException" message="
Method NhanVienDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.NhanVienDaoNGTest_$$_jvstabe_0@3ed03652] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method NhanVienDaoNGTest.testInsertWithEmptyModel()[pri:0, instance:edu.poly.dao.NhanVienDaoNGTest_$$_jvstabe_0@3ed03652] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testInsertWithEmptyModel -->
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testInsertWithNullModel" time="0.0"/>
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testInsertWithValidModel" time="0.001"/>
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testSelect" time="0.004"/>
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testUpdateWithEmptyModel" time="0.001">
    <failure type="org.testng.TestException" message="
Method NhanVienDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.NhanVienDaoNGTest_$$_jvstabe_0@3ed03652] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method NhanVienDaoNGTest.testUpdateWithEmptyModel()[pri:0, instance:edu.poly.dao.NhanVienDaoNGTest_$$_jvstabe_0@3ed03652] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateWithEmptyModel -->
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testUpdateWithNullModel" time="0.0"/>
  <testcase classname="edu.poly.dao.NhanVienDaoNGTest" name="testUpdateWithValidModel" time="0.0"/>
  <testcase classname="edu.poly.dao.ThongKeDaoNGTest" name="testGetBangDiem" time="0.041"/>
  <testcase classname="edu.poly.dao.ThongKeDaoNGTest" name="testGetBangDiemWithMultipleData" time="0.034"/>
  <testcase classname="edu.poly.dao.ThongKeDaoNGTest" name="testGetDiemTheoChuyenDe" time="0.072"/>
  <testcase classname="edu.poly.dao.ThongKeDaoNGTest" name="testGetDiemTheoChuyenDeWithMultipleDate" time="0.065"/>
  <testcase classname="edu.poly.dao.ThongKeDaoNGTest" name="testGetDoanhThu" time="0.08"/>
  <testcase classname="edu.poly.dao.ThongKeDaoNGTest" name="testGetDoanhThuWithMultipleData" time="0.078"/>
  <testcase classname="edu.poly.dao.ThongKeDaoNGTest" name="testGetNguoiHoc" time="0.06"/>
  <testcase classname="edu.poly.dao.ThongKeDaoNGTest" name="testGetNguoiHocWithMultipleDate" time="0.071"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testGetHinh" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.ChuyenDeNGTest.testGetHinh(ChuyenDeNGTest.java:169)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetHinh -->
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testGetHocPhi" time="0.0"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testGetMaCD" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.ChuyenDeNGTest.testGetMaCD(ChuyenDeNGTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetMaCD -->
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testGetMoTa" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.ChuyenDeNGTest.testGetMoTa(ChuyenDeNGTest.java:190)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetMoTa -->
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testGetTenCD" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.ChuyenDeNGTest.testGetTenCD(ChuyenDeNGTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetTenCD -->
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testGetThoiLuong" time="0.001"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetHinh" time="0.0"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetHocPhi" time="0.0"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetHocPhiWithNegative" time="0.0">
    <failure type="org.testng.TestException" message="
Method ChuyenDeNGTest.testSetHocPhiWithNegative()[pri:0, instance:edu.poly.model.ChuyenDeNGTest@173797f0] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method ChuyenDeNGTest.testSetHocPhiWithNegative()[pri:0, instance:edu.poly.model.ChuyenDeNGTest@173797f0] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetHocPhiWithNegative -->
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetHocPhiWithZero" time="0.0"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetMaCD" time="0.0"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetMoTa" time="0.0"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetTenCD" time="0.0"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetThoiLuong" time="0.0"/>
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetThoiLuongWithNegative" time="0.0">
    <failure type="org.testng.TestException" message="
Method ChuyenDeNGTest.testSetThoiLuongWithNegative()[pri:0, instance:edu.poly.model.ChuyenDeNGTest@173797f0] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method ChuyenDeNGTest.testSetThoiLuongWithNegative()[pri:0, instance:edu.poly.model.ChuyenDeNGTest@173797f0] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetThoiLuongWithNegative -->
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testSetThoiLuongWithZero" time="0.001">
    <failure type="org.testng.TestException" message="
Method ChuyenDeNGTest.testSetThoiLuongWithZero()[pri:0, instance:edu.poly.model.ChuyenDeNGTest@173797f0] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method ChuyenDeNGTest.testSetThoiLuongWithZero()[pri:0, instance:edu.poly.model.ChuyenDeNGTest@173797f0] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetThoiLuongWithZero -->
  <testcase classname="edu.poly.model.ChuyenDeNGTest" name="testToString" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.ChuyenDeNGTest.testToString(ChuyenDeNGTest.java:211)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testToString -->
  <testcase classname="edu.poly.model.HocVienNGTest" name="testGetDiem" time="0.0"/>
  <testcase classname="edu.poly.model.HocVienNGTest" name="testGetMaHV" time="0.0"/>
  <testcase classname="edu.poly.model.HocVienNGTest" name="testGetMaKH" time="0.0"/>
  <testcase classname="edu.poly.model.HocVienNGTest" name="testGetMaNH" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.HocVienNGTest.testGetMaNH(HocVienNGTest.java:111)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetMaNH -->
  <testcase classname="edu.poly.model.HocVienNGTest" name="testSetDiemWithLarge" time="0.0">
    <failure type="org.testng.TestException" message="
Method HocVienNGTest.testSetDiemWithLarge()[pri:0, instance:edu.poly.model.HocVienNGTest@3c35c345] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method HocVienNGTest.testSetDiemWithLarge()[pri:0, instance:edu.poly.model.HocVienNGTest@3c35c345] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetDiemWithLarge -->
  <testcase classname="edu.poly.model.HocVienNGTest" name="testSetDiemWithNegative" time="0.0">
    <failure type="org.testng.TestException" message="
Method HocVienNGTest.testSetDiemWithNegative()[pri:0, instance:edu.poly.model.HocVienNGTest@3c35c345] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method HocVienNGTest.testSetDiemWithNegative()[pri:0, instance:edu.poly.model.HocVienNGTest@3c35c345] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetDiemWithNegative -->
  <testcase classname="edu.poly.model.HocVienNGTest" name="testSetDiemWithValid" time="0.0"/>
  <testcase classname="edu.poly.model.HocVienNGTest" name="testSetMaHVWithNegative" time="0.0">
    <failure type="org.testng.TestException" message="
Method HocVienNGTest.testSetMaHVWithNegative()[pri:0, instance:edu.poly.model.HocVienNGTest@3c35c345] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method HocVienNGTest.testSetMaHVWithNegative()[pri:0, instance:edu.poly.model.HocVienNGTest@3c35c345] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetMaHVWithNegative -->
  <testcase classname="edu.poly.model.HocVienNGTest" name="testSetMaHVWithValid" time="0.0"/>
  <testcase classname="edu.poly.model.HocVienNGTest" name="testSetMaKHWithNegative" time="0.0">
    <failure type="org.testng.TestException" message="
Method HocVienNGTest.testSetMaKHWithNegative()[pri:0, instance:edu.poly.model.HocVienNGTest@3c35c345] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method HocVienNGTest.testSetMaKHWithNegative()[pri:0, instance:edu.poly.model.HocVienNGTest@3c35c345] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetMaKHWithNegative -->
  <testcase classname="edu.poly.model.HocVienNGTest" name="testSetMaKHWithValid" time="0.0"/>
  <testcase classname="edu.poly.model.HocVienNGTest" name="testSetMaNH" time="0.001"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testGetGhiChu" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.KhoaHocNGTest.testGetGhiChu(KhoaHocNGTest.java:206)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetGhiChu -->
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testGetHocPhi" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testGetMaCD" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.KhoaHocNGTest.testGetMaCD(KhoaHocNGTest.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetMaCD -->
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testGetMaKH" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testGetMaNV" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.KhoaHocNGTest.testGetMaNV(KhoaHocNGTest.java:228)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetMaNV -->
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testGetNgayKG" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testGetNgayTao" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [null] but found [Tue Apr 27 09:23:06 ICT 2021]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [Tue Apr 27 09:23:06 ICT 2021]
at edu.poly.model.KhoaHocNGTest.testGetNgayTao(KhoaHocNGTest.java:251)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- testGetNgayTao -->
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testGetThoiLuong" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetGhiChu" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetHocPhiWithNegative" time="0.0">
    <failure type="org.testng.TestException" message="
Method KhoaHocNGTest.testSetHocPhiWithNegative()[pri:0, instance:edu.poly.model.KhoaHocNGTest@3681037] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method KhoaHocNGTest.testSetHocPhiWithNegative()[pri:0, instance:edu.poly.model.KhoaHocNGTest@3681037] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetHocPhiWithNegative -->
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetHocPhiWithValid" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetHocPhiWithZero" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetMaCD" time="0.001"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetMaKHWithNegative" time="0.0">
    <failure type="org.testng.TestException" message="
Method KhoaHocNGTest.testSetMaKHWithNegative()[pri:0, instance:edu.poly.model.KhoaHocNGTest@3681037] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method KhoaHocNGTest.testSetMaKHWithNegative()[pri:0, instance:edu.poly.model.KhoaHocNGTest@3681037] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetMaKHWithNegative -->
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetMaKHWithValid" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetMaNV" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetNgayKG" time="0.001"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetNgayTao" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetThoiLuongWithNegative" time="0.0">
    <failure type="org.testng.TestException" message="
Method KhoaHocNGTest.testSetThoiLuongWithNegative()[pri:0, instance:edu.poly.model.KhoaHocNGTest@3681037] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method KhoaHocNGTest.testSetThoiLuongWithNegative()[pri:0, instance:edu.poly.model.KhoaHocNGTest@3681037] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetThoiLuongWithNegative -->
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetThoiLuongWithValid" time="0.0"/>
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testSetThoiLuongWithZero" time="0.0">
    <failure type="org.testng.TestException" message="
Method KhoaHocNGTest.testSetThoiLuongWithZero()[pri:0, instance:edu.poly.model.KhoaHocNGTest@3681037] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method KhoaHocNGTest.testSetThoiLuongWithZero()[pri:0, instance:edu.poly.model.KhoaHocNGTest@3681037] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testSetThoiLuongWithZero -->
  <testcase classname="edu.poly.model.KhoaHocNGTest" name="testToString" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [] but found [null (null)]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null (null)]
at edu.poly.model.KhoaHocNGTest.testToString(KhoaHocNGTest.java:273)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- testToString -->
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testGetDienThoai" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NguoiHocNGTest.testGetDienThoai(NguoiHocNGTest.java:142)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetDienThoai -->
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testGetEmail" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NguoiHocNGTest.testGetEmail(NguoiHocNGTest.java:164)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetEmail -->
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testGetGhiChu" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NguoiHocNGTest.testGetGhiChu(NguoiHocNGTest.java:187)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetGhiChu -->
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testGetGioiTinh" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testGetHoTen" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NguoiHocNGTest.testGetHoTen(NguoiHocNGTest.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetHoTen -->
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testGetMaNH" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NguoiHocNGTest.testGetMaNH(NguoiHocNGTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetMaNH -->
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testGetMaNV" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NguoiHocNGTest.testGetMaNV(NguoiHocNGTest.java:209)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetMaNV -->
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testGetNgayDK" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [null] but found [Tue Apr 27 09:23:06 ICT 2021]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [Tue Apr 27 09:23:06 ICT 2021]
at edu.poly.model.NguoiHocNGTest.testGetNgayDK(NguoiHocNGTest.java:232)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- testGetNgayDK -->
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testGetNgaySinh" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testSetDienThoai" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testSetEmail" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testSetGhiChu" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testSetGioiTinh" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testSetHoTen" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testSetMaNH" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testSetMaNV" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testSetNgayDK" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testSetNgaySinh" time="0.0"/>
  <testcase classname="edu.poly.model.NguoiHocNGTest" name="testToString" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NguoiHocNGTest.testToString(NguoiHocNGTest.java:255)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testToString -->
  <testcase classname="edu.poly.model.NhanVienNGTest" name="testGetHoTen" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NhanVienNGTest.testGetHoTen(NhanVienNGTest.java:90)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetHoTen -->
  <testcase classname="edu.poly.model.NhanVienNGTest" name="testGetMaNV" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NhanVienNGTest.testGetMaNV(NhanVienNGTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetMaNV -->
  <testcase classname="edu.poly.model.NhanVienNGTest" name="testGetMatKhau" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NhanVienNGTest.testGetMatKhau(NhanVienNGTest.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testGetMatKhau -->
  <testcase classname="edu.poly.model.NhanVienNGTest" name="testGetVaiTro" time="0.0"/>
  <testcase classname="edu.poly.model.NhanVienNGTest" name="testSetHoTen" time="0.0"/>
  <testcase classname="edu.poly.model.NhanVienNGTest" name="testSetMaNV" time="0.0"/>
  <testcase classname="edu.poly.model.NhanVienNGTest" name="testSetMatKhau" time="0.0"/>
  <testcase classname="edu.poly.model.NhanVienNGTest" name="testSetVaiTro" time="0.0"/>
  <testcase classname="edu.poly.model.NhanVienNGTest" name="testToString" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [] but found [null]
at edu.poly.model.NhanVienNGTest.testToString(NhanVienNGTest.java:136)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- testToString -->
</testsuite> <!-- Command line test -->
